Implement plone.api.addons module
plone/plone.api pull request #506
Opened 2023-05-15 18:44 UTC by ericof

2023-05-15 18:44 UTC, mister-roboto commented
@ericof thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-05-15 20:26 UTC, ericof commented
@jenkins-plone-org please run jobs

2023-05-16 04:43 UTC, davisagli commented on src/plone/api/addon.py
> +        raise InvalidParameterError(f"Value {limit} for parameter mode is not valid.")
```suggestion
        raise InvalidParameterError(f"Parameter {limit=} is not valid.")
```

(will print e.g. "Parameter limit=bogus is not valid.")

2023-05-16 04:43 UTC, davisagli commented on src/plone/api/addon.py
> +def get_addons_ids(limit: str = "") -> List[str]:
```suggestion
def get_addon_ids(limit: str = "") -> List[str]:
```

(Not required, but it reads a bit better in English. here addon is an adjective which modifies ids)

2025-03-12 12:04 UTC, stevepiercy requested changes
Functions aren't linking. See suggestion.

Otherwise, I made consistent formatting and added some line breaks to visually separate code blocks.

I also added a link to the PR preview on RTD in the description.

2025-03-18 05:29 UTC, ujsquared commented
noticed it's just a few changes. Any way I can help this get merged to main?

2025-03-18 06:38 UTC, stevepiercy commented
@ujsquared I'll merge my suggestions to get that out of the way.

This PR is still marked as draft, but now that docs are included, maybe we can "undraft" it? @ericof @davisagli please let us know. Thank you!

2025-03-18 06:40 UTC, stevepiercy commented on docs/addon.md
> +
```suggestion
```

2025-03-18 06:41 UTC, stevepiercy approved these changes
Docs look good. Let's see what tests, pull request preview, and Jenkins have to say.

2025-03-18 06:52 UTC, stevepiercy commented
@jenkins-plone-org please run jobs

2025-03-18 07:00 UTC, stevepiercy commented
Hm, the methods aren't linking in the RTD PR preview. See `api.addon.get_addons()` in https://ploneapi--506.org.readthedocs.build/addon.html.

Ah, this has the same issue as before. See also:

https://ploneapi--506.org.readthedocs.build/api/index.html

@davisagli fixed that in recent PRs, and this PR got `main` merged into it, so I wonder why this PR didn't work correctly? @ujsquared would you please take a look? Here are two PRs that might have a clue:

- https://github.com/plone/documentation/pull/1907/files
- https://github.com/plone/plone.api/pull/573

2025-03-18 07:02 UTC, stevepiercy commented
Here's the build result on RTD. Lots of import errors. Expand `tox -e rtd-preview` step to see the stacktrace.

https://app.readthedocs.org/projects/ploneapi/builds/27544443/

2025-03-18 19:46 UTC, ujsquared commented
> Here's the build result on RTD. Lots of import errors. Expand `tox -e rtd-preview` step to see the stacktrace.
> 
> https://app.readthedocs.org/projects/ploneapi/builds/27544443/

There are around 40 packages that need version pinning.
Adding in ```-c https://dist.plone.org/release/6.0-dev/constraints.txt``` line  to the  `[testenv:plone6docs]`
and `[testenv:rtd-preview]` in  `tox.ini` along with adding in the a pinned version of `plone.staticresources` to `requirements-docs.txt` fixes the issue for me.  

```plone.staticresources==2.1.17```
This is the exact version I pinned down in `requirement-docs`. 
What do you think @stevepiercy ?

2025-03-19 06:04 UTC, ujsquared commented
> @ujsquared there's only one way to find out: push the commit and see if the PR preview builds on RTD.
> 
> I think the pin of `plone.staticresources==2.1.17` in `requirement-docs.txt` is not the ideal workaround. I haven't kept track of all the various issues with constraints. Perhaps @davisagli or @mauritsvanrees can advise?

I don't have write access to this PR, should I make a new one?

2025-03-19 06:17 UTC, stevepiercy commented
> I don't have write access to this PR, should I make a new one?

Yes, please, using `issue-505-addon-module` as the base branch of your PR and opening your PR against this branch instead of `main`. Thank you!

2025-03-24 05:34 UTC, davisagli commented
@jenkins-plone-org please run jobs

2025-03-24 05:36 UTC, davisagli approved these changes
@ujsquared @stevepiercy Thanks for the help finishing this!

I'll run the Plone jenkins jobs (to test all other Plone packages with this change) but don't expect problems there, since this is new code.

2025-03-24 08:25 UTC, stevepiercy requested changes
Mostly just a bunch of s/addon/add-on.

2025-03-24 08:25 UTC, stevepiercy commented on news/505.feature
> +Implement `plone.api.addon` module. @ericof, @ujsquared
```suggestion
Implement `plone.api.addon` module. @ericof, @ujsquared, @stevepiercy
```

2025-03-24 08:25 UTC, stevepiercy commented on pyproject.toml
> +requires = ["setuptools>=68.2,<77"]
What happened in setuptools 77? It might be good to add a comment with that information, with a link to an issue to update the pin when the dust settles.

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +"""API to handle addon management."""
```suggestion
"""API to handle add-on management."""
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    """Addon information."""
```suggestion
    """Add-on information."""
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    :param limit: Limit list of addons.
```suggestion
    :param limit: Limit list of add-ons.
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    """Information about an Addon.
```suggestion
    """Information about an Add-on.
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    :returns: Addon information.
```suggestion
    :returns: Add-on information.
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +        raise InvalidParameterError(f"No addon {addon} found.")
```suggestion
        raise InvalidParameterError(f"No add-on {addon} found.")
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    :param addon: ID of the addon to be installed.
```suggestion
    :param addon: ID of the add-on to be installed.
```

2025-03-24 08:25 UTC, stevepiercy commented on src/plone/api/addon.py
> +    :param addon: ID of the addon to be uninstalled.
```suggestion
    :param addon: ID of the add-on to be uninstalled.
```

2025-03-24 08:28 UTC, stevepiercy approved these changes
Just the one question, otherwise this is good to merge.

2025-03-24 08:29 UTC, stevepiercy commented
@jenkins-plone-org please run jobs

2025-03-24 08:54 UTC, stevepiercy commented on pyproject.toml
> +requires = ["setuptools>=68.2,<77"]
Also this needs to go into `meta.toml`, right?

2025-03-24 11:07 UTC, mauritsvanrees commented on pyproject.toml
> +requires = ["setuptools>=68.2,<77"]
`setuptools` 77 breaks building some/most of our packages, because it changes how you should identify your license.  See https://github.com/plone/meta/issues/273.

The `<77` will be set by reapplying `plone.meta`, so there is no need to change anything in `meta.toml`.

2025-03-24 18:34 UTC, merged