Enhance API docs of portal.translate to show that the domain is optio…
plone/plone.api pull request #510
Opened 2023-05-24 08:53 UTC by thet

…nal in some cases.

2023-05-24 08:53 UTC, mister-roboto commented
@thet thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2023-05-24 08:54 UTC, thet commented on src/plone/api/portal.py
> +                   the Message' domain is used.
Is the intend on this line right or will it fail any docstring formatters?

2023-05-24 10:22 UTC, stevepiercy requested changes
I don't know for sure, but let's try these suggestions. We'll figure it out.

2023-05-24 10:22 UTC, stevepiercy commented on src/plone/api/portal.py
> +    :param domain: i18n domain to use. When `msgid` is a instance of `Message`
docstrings need to follow reST syntax, not MyST syntax. I know, annoying, isn't it?

```suggestion
    :param domain: i18n domain to use. When ``msgid`` is an instance of ``Message``,
```

2023-05-24 10:22 UTC, stevepiercy commented on src/plone/api/portal.py
> +                   the Message' domain is used.
```suggestion
                   then the ``Message``'s domain is used.
```

2023-05-24 10:22 UTC, stevepiercy commented on src/plone/api/portal.py
> +    :type msgid: string | zope.i18nmessageid.Message
I think it is the following, based on this example: https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#python-signatures

```suggestion
    :type msgid: string
    :type msgid: zope.i18nmessageid.Message
```

2023-07-11 15:47 UTC, thet commented
@stevepiercy tnx for the review and sorry for my late reply.
I've updated this PR with your suggestions.

2023-07-12 05:16 UTC, stevepiercy requested changes
Looks good, just a little tweak for the change log, and it is good to go. Thank you!

2023-07-12 05:16 UTC, stevepiercy commented on news/510.documentation
> +Enhance API docs of portal.translate to show that the domain is optional in some cases.
Sprinkle some MyST in there, standardize author.

```suggestion
Enhance API docs of `portal.translate` to show that the domain is optional in some cases. @thet
```

2023-07-12 05:16 UTC, stevepiercy commented on news/510.documentation
> +[thet]
```suggestion
```

2023-07-12 22:03 UTC, thet commented
Thank you! I applied your suggestions. I'm merging.

2023-07-12 22:03 UTC, merged